version: '3.4'

services:
  abpdocker.web.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32100:80"
    volumes:
      - ${APPDATA}/root/Public/abpdocker:/app
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro