version: '3.4'

services:
  abpdocker.web.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32100:80"
    volumes:
      - ./ABPDocker.Web.Host/bin/Release/netcoreapp2.2/publish:/app
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro