version: '3.4'

services:
  abpdocker.web.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "32100:80"
    volumes:
      - ${APPDATA}/root/Public/abpdockerdata:/app/App_Data
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  reverse-proxy:
    proxy:
      - "9090:80"
    volumes:
      - ${APPDATA}/root/Public/Nginx/proxy.conf:/etc/nginx/conf.d/default.conf