version: '3.4'

services:
  abpdocker.web.host:
    image: ${DOCKER_REGISTRY-}abpdockerwebhost
    build:
      context: .
      dockerfile: src/ABPDocker.Web.Host/Dockerfile

   reverse-proxy:
    image: nginx
    depends_on:
      - abpdocker.web.host
    